# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://basti564.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Basti564's website
# Description of the Site
description: Bastians small website and blog
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Website, Basti564
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico
# Language of the website
language: "en"

# URL of the NyanCat APNG
heroimage: /assets/images/NyanCat.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: bastian.schwickert@gmail.com
facebook_username:
twitter_username: basti564
instagram_username: schwickertba
linkedin_username:
github_username: basti564
youtube_channel_id: UC79BGhgRSQdyl9EMdQwwf4w
reddit_username: Basti564
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: G-GMZ4MWP3BY

# Name of the Author
author-name: Bastian
# URL for the Image of the Author
author-image: /assets/images/Avatar.jpg
# 60 Words About the Author
author-about: Hi, this is me, Bastian. I'm 17 years old. I like making FOSS, reverse engineering, "hacking", AI and SDR. Please check out my public projects on my GitHub. Thanks for visiting my website btw.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/basti564

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
